# Generated by Django 4.1.5 on 2023-01-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('background', models.ImageField(null=True, upload_to='back_images/')),
            ],
            options={
                'verbose_name': 'Топ 10 продукт',
                'verbose_name_plural': 'Топ 10 продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('products', models.ManyToManyField(related_name='products', to='base.productgen')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=300)),
                ('img', models.ImageField(null=True, upload_to='product_images/')),
                ('prod', models.ManyToManyField(related_name='prod', to='base.productlist')),
            ],
            options={
                'verbose_name': 'Информация про продукт',
                'verbose_name_plural': 'Информация про продукты',
            },
        ),
    ]
