# Generated by Django 4.1.5 on 2023-01-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
