# Generated by Django 4.1.5 on 2023-01-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
    ]
